Algoritmo "Atividade_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Flávio Eduardo Miranda Correia
// Data atual  : 28/02/2025
Var
   numero1 : real

Inicio
      escreva("Digite um número:")
      leia(numero1)
   se numero1 > 0 então
      escreva("Este número é positivo")
       senão
   se numero1 = 0 entao
      escreva("Este número é igual a 0")
       senão
   se numero1 < 0 entao
      escreva("Este número é negativo")
fimse
fimse
fimse
fimalgoritmo