Algoritmo "Atividade_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Flávio Eduardo Miranda Correia
// Data atual  : 28/02/2025
Var
 R1 : real
 h2 : real
 volume : real

Inicio
       escreva("Escolha o valor do raio(r): ")
          leia(R1)
       escreva("Escolha o valor da altura(h): ")
          leia(h2)
    volume <- R1* R1 * pi * h2
    escreva("O volume do cilindro é igual à: ")
    escreva(volume)

Fimalgoritmo