Algoritmo "Atividade_1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Autor(a)    : Flávio Eduardo Miranda Correia
// Data atual  : 28/02/2025
Var
    numero1 : real
    numero2 : real
    positivo : real
Inicio
      escreva("Escolha o primeiro numero: ")
       leia(numero1)
      escreva("Escolha outro numero: ")
       leia(numero2)
     positivo := abs(numero1 - numero2)
      escreva("A distância dos números escolhidos é igual à: ")
      escreva(positivo)
      
Fimalgoritmo